# Generated by Django 5.1 on 2024-08-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_contrato', models.CharField(choices=[('longo', 'Longo Prazo'), ('medio', 'Médio Prazo'), ('curto', 'Curto Prazo'), ('diaria', 'Diária')], max_length=10)),
                ('descricao', models.TextField()),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='anuncios/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
