# Generated by Django 5.1 on 2024-09-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios_s', '0003_alter_anuncio_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
