# Generated by Django 5.1 on 2024-09-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
